### ISSUE TITLE
Different weight definition on README.md and api.spec.yaml

### ISSUE THREAD

**Issue by AbelSanchezTuya** [Rviewer-Challenges/skeleton-py-flask-rest#6]
**Describe the bug**
It is not a real bug, but on the *README.md* file the weight is defined as: `click will perform 7 times better than a view` while on the *api.spec.yaml* as: ` Wi = [total_views * 0.3] + [total_clicks * 0.7]` it means each click counts 7/3 times more than the views.

**Comment by mgomez-getwith** [comment]
Hey @AbelSanchezTuya , thanks for reporting the issue (and sorry for the late reply)! 🙏 

We will fix it in the readme of the challenge.

Cheers,
